services:

 yugabytedb:
  image: yugabytedb/yugabyte:2024.1.0.0-b129
  command: >
      yugabyted start
      --background=false
      --tserver_flags=enable_ysql_conn_mgr=false,pg_client_use_shared_memory=true,ysql_colocate_database_by_default=false,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true
  environment:
   - YSQL_DB=db
  ports:
   - 7000:7000
   - 9000:9000
   - 15433:15433
  healthcheck:
      interval: 5s
      timeout: 3s
      test: postgres/bin/pg_isready -h $$(hostname)
 yugabytedb-cli:
  image: postgres
  depends_on:
   yugabytedb:
    condition: service_healthy
  deploy:
    replicas: 0
  command: >
      psql -e 
           -h yugabytedb -p 5433 -U yugabyte -d db
 cockroachdb:
  image: cockroachdb/cockroach
  command: >
    bash -c "cockroach start-single-node --insecure"
  healthcheck:
      interval: 5s
      timeout: 3s
      test: cockroach sql --insecure -e ""
 cockroachdb-cli:
  image: postgres
  depends_on:
   cockroachdb:
    condition: service_healthy
  deploy:
    replicas: 0
  command: >
      psql -e 
           -h cockroachdb -p 26257 -U root -d defaultdb

 oracle:
  image: gvenzl/oracle-free:slim
  environment:
   - ORACLE_PASSWORD=oracle
  healthcheck:
      interval: 5s
      timeout: 3s
      test: echo | sqlplus system/oracle@//localhost/FREEPDB1
  deploy:
    replicas: 0 # don't start by default - too long
 oracle-cli:
  image: container-registry.oracle.com/database/sqlcl:latest
  depends_on:
   oracle:
    condition: service_healthy
  deploy:
    replicas: 0 
  command: >
      -s system/oracle@//oracle/FREEPDB1

 postgres:
  image: postgres
  environment:
   - POSTGRES_PASSWORD=postgres
  healthcheck:
      interval: 5s
      timeout: 3s
      test: pg_isready -h $$(hostname)
 postgres-cli:
  image: postgres
  environment:
   - PGPASSWORD=postgres
  depends_on:
   postgres:
    condition: service_healthy
  deploy:
    replicas: 0
  command: >
      psql -e 
           -h postgres -p 5432 -U postgres 

